export const couponsData = [
  {
    id: "CPN001",
    code: "WELCOME100",
    name: "Welcome Offer",
    description: "₹100 off for new customers.",
    discountType: "Flat",
    discountValue: 100,
    minimumOrder: 500,
    maximumDiscount: 100,
    usageLimit: 500,
    usedCount: 142,
    customerLimit: 1,
    customerType: "New",
    applicableServices: [
      "Wash & Fold",
      "Ironing",
    ],
    startDate: "2026-07-01",
    endDate: "2026-08-31",
    status: "Active",
  },

  {
    id: "CPN002",
    code: "SAVE20",
    name: "Save 20%",
    description: "20% discount on all services.",
    discountType: "Percentage",
    discountValue: 20,
    minimumOrder: 1000,
    maximumDiscount: 300,
    usageLimit: 1000,
    usedCount: 526,
    customerLimit: 2,
    customerType: "All",
    applicableServices: [
      "Wash & Fold",
      "Dry Cleaning",
      "Steam Press",
    ],
    startDate: "2026-07-15",
    endDate: "2026-09-30",
    status: "Active",
  },

  {
    id: "CPN003",
    code: "FIRST50",
    name: "First Order",
    description: "Flat ₹50 discount.",
    discountType: "Flat",
    discountValue: 50,
    minimumOrder: 300,
    maximumDiscount: 50,
    usageLimit: 300,
    usedCount: 97,
    customerLimit: 1,
    customerType: "New",
    applicableServices: [
      "Wash & Fold",
    ],
    startDate: "2026-07-10",
    endDate: "2026-08-20",
    status: "Active",
  },

  {
    id: "CPN004",
    code: "FEST25",
    name: "Festival Sale",
    description: "Festival season coupon.",
    discountType: "Percentage",
    discountValue: 25,
    minimumOrder: 1500,
    maximumDiscount: 500,
    usageLimit: 1500,
    usedCount: 0,
    customerLimit: 3,
    customerType: "All",
    applicableServices: [
      "Premium Wash",
      "Dry Cleaning",
    ],
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    status: "Scheduled",
  },

  {
    id: "CPN005",
    code: "DRY10",
    name: "Dry Cleaning Discount",
    description: "10% off Dry Cleaning.",
    discountType: "Percentage",
    discountValue: 10,
    minimumOrder: 400,
    maximumDiscount: 150,
    usageLimit: 600,
    usedCount: 228,
    customerLimit: 5,
    customerType: "Existing",
    applicableServices: [
      "Dry Cleaning",
    ],
    startDate: "2026-06-01",
    endDate: "2026-09-01",
    status: "Active",
  },

  {
    id: "CPN006",
    code: "IRON50",
    name: "Ironing Offer",
    description: "₹50 off Ironing.",
    discountType: "Flat",
    discountValue: 50,
    minimumOrder: 250,
    maximumDiscount: 50,
    usageLimit: 400,
    usedCount: 392,
    customerLimit: 2,
    customerType: "All",
    applicableServices: [
      "Ironing",
    ],
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    status: "Expired",
  },

  {
    id: "CPN007",
    code: "PREMIUM15",
    name: "Premium Care",
    description: "15% off Premium Wash.",
    discountType: "Percentage",
    discountValue: 15,
    minimumOrder: 800,
    maximumDiscount: 250,
    usageLimit: 700,
    usedCount: 184,
    customerLimit: 2,
    customerType: "Existing",
    applicableServices: [
      "Premium Wash",
    ],
    startDate: "2026-07-05",
    endDate: "2026-10-05",
    status: "Active",
  },

  {
    id: "CPN008",
    code: "STEAM99",
    name: "Steam Press Special",
    description: "₹99 off Steam Press.",
    discountType: "Flat",
    discountValue: 99,
    minimumOrder: 600,
    maximumDiscount: 99,
    usageLimit: 350,
    usedCount: 78,
    customerLimit: 1,
    customerType: "All",
    applicableServices: [
      "Steam Press",
    ],
    startDate: "2026-07-20",
    endDate: "2026-08-20",
    status: "Active",
  },

  {
    id: "CPN009",
    code: "REFER200",
    name: "Referral Bonus",
    description: "₹200 referral coupon.",
    discountType: "Flat",
    discountValue: 200,
    minimumOrder: 1200,
    maximumDiscount: 200,
    usageLimit: 250,
    usedCount: 65,
    customerLimit: 1,
    customerType: "Existing",
    applicableServices: [
      "Wash & Fold",
      "Dry Cleaning",
    ],
    startDate: "2026-07-01",
    endDate: "2026-12-31",
    status: "Active",
  },

  {
    id: "CPN010",
    code: "SUMMER30",
    name: "Summer Campaign",
    description: "30% off selected services.",
    discountType: "Percentage",
    discountValue: 30,
    minimumOrder: 1800,
    maximumDiscount: 600,
    usageLimit: 1000,
    usedCount: 0,
    customerLimit: 2,
    customerType: "All",
    applicableServices: [
      "Premium Wash",
      "Steam Press",
      "Dry Cleaning",
    ],
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    status: "Scheduled",
  },
];