export const reportData = {
  // ================= Summary =================
  summary: [
    {
      title: "Total Revenue",
      value: 325870,
      change: "+12.4%",
      trend: "up",
      icon: "revenue",
    },
    {
      title: "Total Orders",
      value: 1248,
      change: "+8.2%",
      trend: "up",
      icon: "orders",
    },
    {
      title: "Completed Orders",
      value: 1132,
      change: "+5.4%",
      trend: "up",
      icon: "completed",
    },
    {
      title: "Pending Orders",
      value: 68,
      change: "-2.1%",
      trend: "down",
      icon: "pending",
    },
    {
      title: "Cancelled Orders",
      value: 48,
      change: "-1.4%",
      trend: "down",
      icon: "cancelled",
    },
    {
      title: "Customers",
      value: 684,
      change: "+9.8%",
      trend: "up",
      icon: "customers",
    },
  ],

  // ================= Monthly Report =================
  monthlyReport: [
    {
      id: 1,
      month: "January",
      orders: 182,
      revenue: 45280,
      averageOrder: 249,
      discount: 1800,
      growth: 5.8,
    },
    {
      id: 2,
      month: "February",
      orders: 194,
      revenue: 48320,
      averageOrder: 249,
      discount: 1950,
      growth: 6.7,
    },
    {
      id: 3,
      month: "March",
      orders: 228,
      revenue: 56780,
      averageOrder: 249,
      discount: 2300,
      growth: 17.5,
    },
    {
      id: 4,
      month: "April",
      orders: 246,
      revenue: 61840,
      averageOrder: 251,
      discount: 2450,
      growth: 8.9,
    },
    {
      id: 5,
      month: "May",
      orders: 188,
      revenue: 48760,
      averageOrder: 259,
      discount: 2100,
      growth: -21.1,
    },
    {
      id: 6,
      month: "June",
      orders: 210,
      revenue: 53980,
      averageOrder: 257,
      discount: 2280,
      growth: 10.7,
    },
  ],

  // ================= Service Report =================
  serviceReport: [
    {
      id: 1,
      service: "Wash & Fold",
      category: "Laundry",
      unit: "Kg",
      quantity: 840,
      orders: 395,
      revenue: 94500,
      averagePrice: 239,
    },
    {
      id: 2,
      service: "Dry Cleaning",
      category: "Premium",
      unit: "Piece",
      quantity: 275,
      orders: 275,
      revenue: 82650,
      averagePrice: 301,
    },
    {
      id: 3,
      service: "Steam Ironing",
      category: "Ironing",
      unit: "Piece",
      quantity: 525,
      orders: 525,
      revenue: 42000,
      averagePrice: 80,
    },
    {
      id: 4,
      service: "Express Wash",
      category: "Laundry",
      unit: "Kg",
      quantity: 210,
      orders: 98,
      revenue: 28600,
      averagePrice: 292,
    },
    {
      id: 5,
      service: "Shoe Cleaning",
      category: "Cleaning",
      unit: "Pair",
      quantity: 58,
      orders: 58,
      revenue: 14500,
      averagePrice: 250,
    },
    {
      id: 6,
      service: "Carpet Cleaning",
      category: "Premium",
      unit: "Piece",
      quantity: 32,
      orders: 32,
      revenue: 25620,
      averagePrice: 800,
    },
  ],

  // ================= Payment Report =================
  paymentReport: [
    {
      method: "UPI",
      transactions: 485,
      amount: 178450,
      percentage: 55,
      color: "#22C55E",
    },
    {
      method: "Cash",
      transactions: 201,
      amount: 74200,
      percentage: 23,
      color: "#3B82F6",
    },
    {
      method: "Card",
      transactions: 138,
      amount: 45200,
      percentage: 14,
      color: "#F59E0B",
    },
    {
      method: "Wallet",
      transactions: 54,
      amount: 18420,
      percentage: 6,
      color: "#8B5CF6",
    },
    {
      method: "Pending",
      transactions: 27,
      amount: 5600,
      percentage: 2,
      color: "#EF4444",
    },
  ],

  // ================= Top Customers =================
  topCustomers: [
    {
      id: 1,
      name: "Rahul Kumar",
      phone: "+91 9876543210",
      orders: 28,
      revenue: 8420,
      lastOrder: "2026-07-20",
    },
    {
      id: 2,
      name: "Anjali Nair",
      phone: "+91 9876543211",
      orders: 24,
      revenue: 7980,
      lastOrder: "2026-07-22",
    },
    {
      id: 3,
      name: "Muhammed Ali",
      phone: "+91 9876543212",
      orders: 22,
      revenue: 7450,
      lastOrder: "2026-07-19",
    },
    {
      id: 4,
      name: "Aisha",
      phone: "+91 9876543213",
      orders: 19,
      revenue: 6890,
      lastOrder: "2026-07-23",
    },
    {
      id: 5,
      name: "Sneha",
      phone: "+91 9876543214",
      orders: 17,
      revenue: 6240,
      lastOrder: "2026-07-18",
    },
  ],

  // ================= Top Services =================
  topServices: [
    {
      rank: 1,
      service: "Wash & Fold",
      revenue: 94500,
      orders: 395,
    },
    {
      rank: 2,
      service: "Dry Cleaning",
      revenue: 82650,
      orders: 275,
    },
    {
      rank: 3,
      service: "Steam Ironing",
      revenue: 42000,
      orders: 525,
    },
    {
      rank: 4,
      service: "Express Wash",
      revenue: 28600,
      orders: 98,
    },
    {
      rank: 5,
      service: "Carpet Cleaning",
      revenue: 25620,
      orders: 32,
    },
  ],
};